"""'acticles'

Revision ID: 7302a24c95ae
Revises: 774d5209526c
Create Date: 2023-04-21 22:30:22.883471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7302a24c95ae'
down_revision = '774d5209526c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
