"""empty message

Revision ID: 774d5209526c
Revises: 7f71cb6d1432
Create Date: 2023-04-21 22:07:45.251707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774d5209526c'
down_revision = '7f71cb6d1432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
